# Configuração PostgreSQL
spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    hikari:
      connection-timeout: 30000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

## Configuração do Servidor (Context Path)
#server:
#  servlet:
#    context-path: /api
#
## Configuração Swagger (Springdoc OpenAPI)
#springdoc:
#  api-docs:
#    path: /api-docs
#  swagger-ui:
#    path: /swagger-ui.html
#    url: /api/api-docs
#    config-url: /api/api-docs/swagger-config
#    operations-sorter: method
